### ISSUE TITLE
Add all options to UI

### ISSUE THREAD

**Issue by ethanaobrien** [terreng/simple-web-server#1]
Sorry, this is a lot. I may have missed something (Don't worry about it)

Please add these all to the UI:

Errors:

Custom 400 html: optCustom400 (default: false, boolean)
400 html location: optCustom400location (default: /400.html, string)
Custom 401 html: optCustom401 (default: false, boolean)
401 html location: optCustom401location (default: /401.html, string)
Custom 403 html: optCustom403 (default: false, boolean)
403 html location: optCustom403location (default: /403.html, string)
Custom 404 html: optCustom404 (default: false, boolean)
404 html location: optCustom404location (default: /404.html, string)
Send 404 variable: optCustom404usevar (default: false, boolean)
404 variable name: optCustom404usevarvar (default: locationoflostuser, string)

Exclude .html:

Exclude .html extension: optExcludeDotHtml (default: false, boolean)
Exclude .htm extension: optExcludeDotHtm (default: false, boolean)

Index rendering:

Auto render index.html (already implemented, don’t change this)
404 instead of directory listing: optDir404 (default: false, boolean)

Directory listing:

Static directory listing (no JavaScript): optStatic (default: false, boolean)
Show dot files in directory listing: optDotFilesDirListing (default: false, boolean)

Other:
Send cache control header with every request: optCacheControl (default: false, boolean)
Cache control header value: optCacheControlValue (default: must-revalidate, string)

Htaccess:

Scan for htaccess: optScanForHtaccess (default: false, boolean) - with this one, please add a place that we can add a link to the htaccess readme 
Allow GET requests: optGETHtaccess (default: false, boolean)
Allow PUT/POST requests: optPUTPOSTHtaccess (default: false, boolean)
Allow DELETE requests: optDELETEHtaccess (default: false, boolean)
Show in directory listing: optDirListingHtaccess (default: false, boolean)

File upload/delete: 

Allow file upload: optUpload (default: false, boolean)
Allow replace file: optAllowReplaceFile (default: false, boolean)
Allow deleting files: optDelete (default: false, boolean)

IP blocking:

Search for IP block list: optIpBlocking (default: false, boolean)
Ip block list location: optIpBlockList (default: ipblock.list, string)
Block requests from undefined addresses: optIpBlockUndefined (default: false, boolean)
Please also add a place to put a link to the readme

Auth:

Use basic auth: optUsebasicauth (default: false, boolean)
Auth username: optAuthUsername (default: admin, string)
Auth password: optAuthPassword (default: admin, string)

Protocol options: (do not do at the moment)

Use https: optUseHttps (default: false, boolean)
Forward to https: optHttp2Https (default: false, boolean)
Use http 2.0: optHttp2 (default: false, boolean)

For https and http 2, please have places where we can generate keys required for protocol (could you please work on the key generation? I plan to use the nodejs `require('https')` and `require('http2')`)

Let me know if you need anything

**Comment by ethanaobrien** [comment]
@terreng 

Scrap the https and http2 options for now. I'm running into trouble and do not plan to do it in the first release. 

Also, could I have a status update?

**Comment by terreng** [comment]
I see that most of the inputs are either checkboxes or text boxes, but there are a few that I'm not sure what they are or what values would be valid:

optCustom404usevarvar: Is this a text field?
optCacheControlValue: I assume this is a dropdown. What are the valid values?
optIpBlockList: What kind of input is this?

I am a little busy at the moment, but I can get the UI part done once you've finished the web server part.

**Comment by ethanaobrien** [comment]
@terreng Very sorry, I didnt think about including that. I updated the initial commit and added either Boolean or string for each option

**Comment by ethanaobrien** [comment]
@terreng 

Sorry, forgot one category of options

Mod Rewrite:
mod-rewrite: optModRewriteEnable (default: false, boolean)
Regular Expression: optModRewriteRegexp (default: `.*\\.[\\d\\w]+$`, string) (Please note, in the default I have replaces \ with \\ so the string works properly when copied and pasted)
Negate Regexp: optModRewriteNegate (default: false, boolean)
Rewrite To: optModRewriteTo (default: /index.html, string)

**Comment by terreng** [comment]
Is the negate regex option necessary? I think this negation be accomplished in the regex itself by using a negative lookahead or something.

For the options that take a file path (like optModRewriteTo), do we need any validation? Or is any string valid?

**Comment by ethanaobrien** [comment]
I don't really know to be honest, I just just copied from the web server for chrome app. 

Also, I think I have a solution to the console problem. 
(I would put this comment in the pull request but I do not have access at the moment)
So the problem is that we need a way for developers to view the console log when using server side POST. My solution is to have the server run in the window, instead of the main process. The reason I ask first is because it requires enabling node integration and disabling context isolation but I think it is a good solution, as the user could just open the console by pressing ctrl shift i

**Comment by terreng** [comment]
Having the server run in the window is a bad idea.

We can just build our own log viewer into the app.

**Comment by ethanaobrien** [comment]
I think that is a good idea, the only problem is I'm worried about if the user logs a json string. If we sent the console function to the main process from the window, and then if we re-declared the console function, would the server log to the window?

**Comment by terreng** [comment]
I'm not really sure what you mean. Could you back up a little bit and explain how logging would work and the purpose of it? I don't think we're on the same page here.

**Comment by ethanaobrien** [comment]
Yes, sorry. I would like a way for developers to be able to open the console and view logs made by either incoming requests and by debugging server side post/get requests. I would like to find a way to log through the window, without having the app there. Especially with large json strings, it would make it easier to search the logs. If I still doesn't make sense, just let me know.

**Comment by terreng** [comment]
Are these logs generated by the server code? Is there any way for people to create their own custom logs?

**Comment by ethanaobrien** [comment]
Some logs are generated by the server code, like when a resource is requested. I think defining server side post with help with the understanding. I built server side post with security as my first priority. When I first got the idea, I discarded it because I thought that hackers would be able to upload a file and perform a post request to it, exposing the entire computer. I then did lots of thinking and came upon the idea of validating the script via a key found in the file and inside the htaccess file. Requests toward htaccess files are blocked by default. The server takes the file, searches for the key, checks if the key is the same as the key in the htaccess file, and then, once everything is good, the server uses eval to run the script. The part that I am worried about is developers being able to test parts of the script using the console.log. To answer your question, yes, the user could use a custom log function in each file, but I am also working to make this feature easier. If possible, I wish to aim the console function towards the app window, logging what happens in the app. I see that you can push values from the window to the main process (through the saving feature) would it be possible to do the opposite? To call a function in the window, from the main process that will log to the console? I think this method would be the best way to go.

**Comment by terreng** [comment]
> would it be possible to do the opposite? To call a function in the window, from the main process that will log to the console?

Yes, this is possible.

Do you think that maybe this feature can wait until version 2?

**Comment by ethanaobrien** [comment]
Sure! Also, I would like to be the one to do this feature. Could you give me some references? I think all that needs to be finished in preparation for version 1 is the Ui. (Should we have an update checker?)

**Comment by terreng** [comment]
> Should we have an update checker

I'm not sure. It makes sense for pushing out future releases, but I also think it would be nice if the program didn't have any telemetry.

**Comment by ethanaobrien** [comment]
@terreng 
I think we should at least have something telling the user if it is outdated. Not doing so could expose the user to bugs/vulnerabilities that have been fixed. We could do something like I have [here](https://github.com/ethanaobrien/youtube-downloader) where it just fetches version.json located in the github repository and then just alerts the user. The full code is below.

```
        fetch('https://raw.githack.com/ethanaobrien/youtube-downloader/main/version.json').then(response => {
            if (response.ok) {
                response.text().then(body => {
                    var version = JSON.parse(body);
                    var usingVersion = '1.3';
                    if (usingVersion != version.current_version) {
                        alert('[ytdl] You have version '+usingVersion+' but the newest version is ' + version.current_version);
                        if (confirm('[ytdl] Do you want to update? (Github Pages will open)')) {
                            window.open('https://ethanaobrien.github.io/youtube-downloader/index.html');
                        };
                    };
                });
            };
        });
```

**Comment by terreng** [comment]
I can implement an auto-updater that checks for and downloads any updates when you open the app. 

I think it would be better if the UI showed a banner or something with a button to update, but it was optional.

**Comment by ethanaobrien** [comment]
I like that Idea, I think we should do it.

**Comment by terreng** [comment]
@ethanaobrien 

For `optCustom400location`, `optCustom401location`, `optCustom403location`, and `optCustom404location`: How should these be validated? What I mean by that is, what is the user allowed to type into the text box? What characters are allowed? What will happen if they enter a bunch of random characters like `!@#$%^&*()`?

Could you explain what `optCustom404usevar` and `optCustom404usevarvar` do? Also, what characters are valid for `optCustom404usevarvar`?

Is `optIpBlockList` a path to a file of blocked IPs?

For mod rewrite, by far the most common use case for this is for Single Page Applications. Can you think of any other reason someone would use this option? Turning on mod rewrite with the default settings has the same effect as changing `optCustom404location` to `index.html` right? The result being that any path which isn't found will serve index.html instead.

In the current version of this program, I have a single checkbox for using index.html as the 404 page. I think this is much more user friendly because its a super common use case. What do you think about keeping it?

I'm going to hide most of these options in an "Advanced" section. I like the way you organized the options, I'm going to try and organize them into similar sections to make things easier to find.

**Comment by ethanaobrien** [comment]
@terreng 
All great questions.

>For optCustom400location, optCustom401location, optCustom403location, and optCustom404location: How should these be validated? What I mean by that is, what is the user allowed to type into the text box? What characters are allowed? What will happen if they enter a bunch of random characters like !@#$%^&*()?

I have multiple failsafe's in place already. Any character will be caught and an incorrect input will also be caught.

>Could you explain what optCustom404usevar and optCustom404usevarvar do? Also, what characters are valid for optCustom404usevarvar?

optCustom404usevar is a boolean (true or false). Determines if the user wants to send a variable along with the 404 html document. Requires custom404 feature to be enabled
optCustom404usevarvar has no failsafe in place (the client browser would say invalid code). If you would like to have validation, then any numbers or letters. No special characters.

>Is optIpBlockList a path to a file of blocked IPs?

Correct. If the inputted path is not found, it will log to the console.

>For mod rewrite, by far the most common use case for this is for Single Page Applications. Can you think of any other reason someone would use this option?

Yes, mod rewrite is for SPA's (Single Page Applications). I know of no other reasons

>Turning on mod rewrite with the default settings has the same effect as changing optCustom404location to index.html right? The result being that any path which isn't found will serve index.html instead.

This is correct. Auto render index options will not work in this case.

>In the current version of this program, I have a single checkbox for using index.html as the 404 page. I think this is much more user friendly because its a super common use case. What do you think about keeping it?

I don't think that we should have an option to use the index.html as the 404 page. All relative urls are broken when this is used. If you decode to do it anyway, let me know so that I can make this into the server

>I'm going to hide most of these options in an "Advanced" section. I like the way you organized the options, I'm going to try and organize them into similar sections to make things easier to find.

Awesome!

**Comment by terreng** [comment]
For `optCustom404usevarvar`, does that include spaces and/or capital letters?
Also, I still don't really get what this option does. What is the variable for? What does it contain?

If the only reason we know of to use mod rewrite is for SPAs, then I think we should rename it to "Single page rewrite". If you enable it, then you can change the file it rewrites to. Under that I'll put the advanced option to customize the regex, which I imagine most people won't ever touch.

**Comment by ethanaobrien** [comment]
@terreng 

>For optCustom404usevarvar, does that include spaces and/or capital letters?
Also, I still don't really get what this option does. What is the variable for? What does it contain?

Yes, any case, no spaces. This field will be sent with the html. Ill use an example. The server will add the following line to the top of the response `'<script>window.' + this.app.opts.optCustom404usevarvar + ';</script>'`

>If the only reason we know of to use mod rewrite is for SPAs, then I think we should rename it to "Single page rewrite". If you enable it, then you can change the file it rewrites to. Under that I'll put the advanced option to customize the regex, which I imagine most people won't ever touch.

Yeah, I agree. I havent ever used it (I dont know that kind of stuff)

Also, Can I have a status update?

**Comment by terreng** [comment]
What's the use case for `optCustom404usevarvar`? Why would somebody want that?

I wanted to make sure I understood what every option is supposed to do before I started. I'm going to do other UI improvements to the app too. I want to make it look good. I'm going to follow material design because the original app did and I think it looks nice. So it will take me a little longer to do more design work but it will still be pretty simple.

**Comment by ethanaobrien** [comment]
The reason I put the 404 variable is because it is an easy and efficient way to send the location the user requested. You could also do it via window.location though. I use it because I find it more clean.


Also, thanks for the status update

**Comment by terreng** [comment]
> send the location the user requested

I still don't understand what it does. Could you clarify?

**Comment by ethanaobrien** [comment]
Yeah, sorry. If the user requests something like localhost:8887/some/directory and there is a 404 error, then the 404 variable will be '/some/directory'. The user could then use this variable to set the inner HTML of an object to the requested path

**Comment by terreng** [comment]
Okay, so the 404 variable is injected as javascript into the 404 html page that is returned? And if the user has a custom 404 page, they could read the variable in javascript and insert it onto the page?

**Comment by ethanaobrien** [comment]
Correct. The variable is only for the custom 404 page and has no effect is custom 404 is not on

**Comment by terreng** [comment]
> Correct. The variable is only for the custom 404 page and has no effect is custom 404 is not on

Using javascript to insert the path like this is bad practice, because the user could have javascript disabled. Instead, here's what I think we should do: Read the custom 404 html file, look for a custom string the user can specify to be replaced with the path and replace it if found, and then serve it.

For example, I could change `optCustom404location` to point to a file that looks something like this:

```html
<html>
  <head>
    <title>404: Not Found</title>
  </head>
  <body>
    <h1>Error 404: Not Found</h1>
    <h2>The following path was not found in this server: {{PATH}}</h2>
  </body>
</html>
```

And then I could change `optCustom404ReplaceString` to `{{PATH}}`. It would be dynamically replaced with the current path, no JavaScript required. Just make sure to html escape it.

What do you think?

**Comment by ethanaobrien** [comment]
Sounds smart, I'll do that

**Comment by terreng** [comment]
Does the directory listing automatically detect if javascript is disabled and use the static version instead?

The custom replace string option should work for all the error pages, not just 404. But let's just have one option for all of them, not individual options for each.

Also, the replacement string should be able to show up more than once in the file, so make sure to replace all occurrences.

**Comment by ethanaobrien** [comment]
@terreng 
>Does the directory listing automatically detect if javascript is disabled and use the static version instead?

No, do you know how to redirect to `?static=1` when javascript is disabled?

>The custom replace string option should work for all the error pages, not just 404. But let's just have one option for all of them, not individual options for each.

Good idea. I would just need to change like 2 lines of code

>Also, the replacement string should be able to show up more than once in the file, so make sure to replace all occurrences.

Thanks for letting me know


Also, could you add a note telling the user how to use it?

**Comment by terreng** [comment]
What exactly is javascript needed for on the directory listing?

And yes, I'm going to add an explainer for all of the options and I'll let you know if there are any more that I need clarification on.

**Comment by ethanaobrien** [comment]
@terreng 

>What exactly is javascript needed for on the directory listing?

Making it look nice, sorting files by name, adding the files to the list, to show or hide parent directory button

There is an option where the user can use static directory listing

**Comment by terreng** [comment]
The much much better solution would be to have a single directory listing page that works without JavaScript but is better if you have it enabled. Instead of having two different versions, just have one. This is called progressive enhancement.

Load in the static version by default, and then if the script runs, apply the enhancements to the page. That way, if the script doesn't run, the page has already has a static version.

This isn't something we have to do for the initial release, but I really think we should rather than having an option for it.

**Comment by ethanaobrien** [comment]
@terreng 

>Load in the static version by default, and then if the script runs, apply the enhancements to the page. That way, if the script doesn't run, the page has already has a static version.

So I could modify the way the server sends the directory listing to where it would send static but just set the display to none on the template and I could just use javascript to switch what is being shown? Cool!
I'll add this to my pull request. You need to change nothing

I would also like to have an option for users who want the static listing. It wouldn't hurt to have the option

**Comment by terreng** [comment]
> I would also like to have an option for users who want the static listing. It wouldn't hurt to have the option

Sure. We can call it "Always use static directory listing"

**Comment by ethanaobrien** [comment]
@terreng 

I have made this into the server.

`optStaticjs`: Boolean, Will send JavaScript directory listing with backup static directory listing
Default: false

I would like this option to be false because the screen flashes when the page initially loads

**Comment by terreng** [comment]
We should send them both together by default. Don't worry about a flicker, I can fix that.

**Comment by ethanaobrien** [comment]
@terreng How could you fix the flicker? I dont feel comfortable setting this option to true as default.

**Comment by terreng** [comment]
Maybe we're not on the same page about how this would work.

The HTML page that is returned should be static and should already have all of the data about the directory listing inside it. Then if the JavaScript loads, you can hide the static container and display the interactive one instead.

The entire page should be served in one HTML file. No need for any other requests to get the script, css, or anything else. So it should all be able to load at the same time.

Is the JavaScript currently making additional requests to the server?

**Comment by ethanaobrien** [comment]
>Is the JavaScript currently making additional requests to the server?

No, the JavaScript directory listing makes no additional requests to the server. 

>The HTML page that is returned should be static and should already have all of the data about the directory listing inside it. Then if the JavaScript loads, you can hide the static container and display the interactive one instead.

This is what I do. The flash is caused on first load by transitioning from displaying the static to the javascript one

I still think this should be false by default. I feel like something like this shouldnt be used very often.

I just pushed my changes. Take a look at #10 This has the static directory listing. Just request `/?staticjs=1`

**Comment by terreng** [comment]
I think we should have this on by default. I'm not worried about the flash because I can fix that.

**Comment by ethanaobrien** [comment]
Okie, just set the default to true

Also, #10 is ready o merge

**Comment by terreng** [comment]
- [ ] Fix static load flicker and reverse static option
- [ ] #11 - Change 404 var to replace string

**Comment by terreng** [comment]
Would it be okay if I removed the "opt" part from all of these option names?

**Comment by ethanaobrien** [comment]
@terreng Sure, although please go into `WSC.js` and `index.js` and use find and replace to replace all

Example:
Find `optScanForHtaccess` and replace with `ScanForHtaccess`

**Comment by terreng** [comment]
Sure thing! I'm going to lowercase the first character. So `optScanForHtaccess` will become `scanForHtaccess`.
I might also adjust the camel casing a little bit for a few of them to make it consistent.

**Comment by ethanaobrien** [comment]
@terreng Could you give me a status update?

**Comment by terreng** [comment]
We're not doing `optHttp2Https` right?

**Comment by terreng** [comment]
What's the point of the "Exclude .html extension" option?

IP blocking seems very advanced, so I don't think I'm going to include those options in the UI (will require manual config editing). Sound good?

**Comment by terreng** [comment]
Do hidden files show up in the directory listing? (Even if they don't have a (.) dot in front?) I think we should consider changing show dot files to show hidden files. What do you think?

**Comment by ethanaobrien** [comment]
@terreng 

>We're not doing optHttp2Https right? What about optHttp2?

Only https option, no https2 or http2


>What's the point of the "Exclude .html extension" option?

To not show the .html extension on html files, when I first made it is seemed sucky but I've grown to really like it


>IP blocking seems very advanced, so I don't think I'm going to include those options in the UI (will require manual config editing). Sound good?

Yes, the IPBlocking is just a boolean input to turn the option on and off and a string input to set the path of the ipblock list. All ipblock is edited in the file, in the ui you just need to put the path to the block list and whether to scan for the file.


>Do hidden files show up in the directory listing? (Even if they don't have a (.) dot in front?) I think we should consider changing show dot files to show hidden files. What do you think?

Hidden files do show in the directory listing. Would you know how to also hide hidden files? It only currently hides dot files. I think as long as it isnt too advanced we should add that to the do not send dot in directory listing option and change the name to the option as you said.

**Comment by terreng** [comment]
I don't think the exclude .html extension feature is common enough to need an option in the UI either.

For IP blocking, I was going to leave it out of the UI completely. We can have a guide on how to edit all the settings in the config json file, including advanced settings that aren't in the UI.

Do you want to look in to not showing hidden files in the directory listing?

**Comment by ethanaobrien** [comment]
>I don't think the exclude .html extension feature is common enough to need an option in the UI either.

I think not putting every option in the UI takes the 'simple' out of simple web server. It is pretty difficult, especially for people first starting out, to change the settings. I tried walking someone through changing the no html option and it never started working. I recommend making a simple function to render the options, meaning a json string we just add the type, default, etc. to and use this to render all the options. It would make adding options a lot easier in the future. I think we should add the .html feature to the UI. From what I've found, most people don't read through the documentation, so not adding all options to the UI would make it to where they wouldn't ever know about these options. Please consider adding everything in the UI. I want this server to be as simple and advanced as possible.

>Do you want to look in to not showing hidden files in the directory listing?

Sure, I'll do that!

**Comment by terreng** [comment]
@ethanaobrien Can you explain what the `optIpBlockUndefined` option does? Is this a way of toggling between a block list and an allow list?

**Comment by terreng** [comment]
@ethanaobrien How does the `optExcludeDotHtml` option work? Does it redirect requests to `/example.html` to `/example`? What if there was already a file at `/example`?

**Comment by terreng** [comment]
In addition to the option to show hidden & dot files in the directory listing, how about an option to serve hidden & dot files at all? I can definitely see not wanting to make these files accessible, and I think we should even consider making this the default. What do you think?

**Comment by terreng** [comment]
Seeing as `.htaccess` files aren't actually formatted the same way we are here, I think we should call them something else. How about`.swsaccess`?

Also, I don't think the `optDirListingHtaccess` option is really necessary if we already have an option to hide dot files.

**Comment by ethanaobrien** [comment]
`optIpBlockUndefined` will block requests with no ip attached to them (Ive had it happen) (true or false)
`optExcludeDotHtml` will yes forward to the url with no `.html` extension. if there is a file at `/example` the html page is rendered, not the file.

>In addition to the option to show hidden & dot files in the directory listing, how about an option to serve hidden & dot files at all? I can definitely see not wanting to make these files accessible, and I think we should even consider making this the default. What do you think?

This can be easily implemented. We'll do this

>Also, I don't think the optDirListingHtaccess option is really necessary if we already have an option to hide dot files.

Yeah I need to change that

>Seeing as .htaccess files aren't actually formatted the same way we are here, I think we should call them something else. How about.swsaccess?

I've thought about changing it before, and I've reached the result not to change it. There isn't technically a `htaccess` file type. Many different web servers format it differently. It does the same thing as an htaccess file which is why I've chosen to keep it.

**Comment by terreng** [comment]
> `optIpBlockUndefined` will block requests with no ip attached to them (Ive had it happen) (true or false)

How can there be a request with no IP?

> I've thought about changing it before, and I've reached the result not to change it. There isn't technically a htaccess file type. Many different web servers format it differently. It does the same thing as an htaccess file which is why I've chosen to keep it.

`.htaccess` is a well defined file format for Apache web servers. Some people who use this program may already have actual `.htaccess` files, so using the same name would conflict. I think we should call it something else to avoid this issue, and prevent confusion about how it is formatted. Do you have any other filename suggestions?

Also, what's the use case for an IP block list? Wouldn't an allow list be more useful instead?

**Comment by ethanaobrien** [comment]
>How can there be a request with no IP?

I do not know. But I've seen it happen on spam requests. (maybe we should just do this by default)

>.htaccess is a well defined file format for Apache web servers. Some people who use this program may already have actual .htaccess files, so using the same name would conflict. I think we should call it something else to avoid this issue, and prevent confusion about how it is formatted. Do you have any other filename suggestions?

The filename is `wsc.htaccess` not `.htaccess`. I did this for 2 reasons
1. It isn't technically an htaccess file, so we have a different name (to resolve conflicts) but having the htaccess extension still tells people what the file does
2. For users on chromeos that use this, because chromeos does not allow naming a file starting with a `.`

I really don't think we should change the name. Having the name end with `htaccess` tells people what it does but the `wsc` part tells people it is slightly different. It would also be a really big pain to rewrite all the readme's and all the code

>Also, what's the use case for an IP block list? Wouldn't an allow list be more useful instead?

Yeah, I need to do this. I also need to support entering things like `192.168.*.*`. Maybe we should set this feature off - it needs a lot of work still

**Comment by terreng** [comment]
It should be a dot file. This app won't be available on Chrome OS, so there's no reason to not start the filename with a period. I think we should call it `.swshtaccess`, but I'm open to other suggestions. Ending the name with `htaccess` tells people what it does, and the `sws` part makes it clear that the format is specific to our program. The text editor you use probably has a a feature replace all across all files in an entire directory. I know it's easy to do in Notepad++ and VSCode.

**Comment by terreng** [comment]
Here's a list of all the options, their config file option names, and how I plan on organizing them in the UI. Please let me know if you have any feedback before I move forward in adding all these options to the UI!

<h1 style="color: rgb(0, 0, 0); font-family: Times; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Basic options</h1>

Option | Name | Value | Default | Description
-- | -- | -- | -- | --
Enabled | enabled | true/false | - | Whether the server is turned on or not
Directory | path | path string | - | Directory to serve files from
Port | port | number 1 - 65535 | 8080 | Port that server is accessible on
Accessible on local network | localnetwork | true/false | false | Makes the web server accessible over LAN to other computers on the network. Access using this computer's local IP address.

<h1 style="color: rgb(0, 0, 0); font-family: Times; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Basic rules</h1>

Option | Name | Value | Default | Description
-- | -- | -- | -- | --
Automatically show index.html | showIndex | true/false | true | Automatically serve index.html file when no file path is specified
Single page rewrite (for SPA) | spa | true/false | false | Automatically rewrite all paths that don't match files to index.html in root directory. For Single Page Applications.
Show directory listing | directoryListing | true/false | true | Show a list of files in the specified directory instead of a 404 page
Exclude .html extension | excludeDotHtml | true/false | false | Exclude .htm and .html extensions from URLs. For example, forwards /example.html to /example. If a file exists at the path without an extension, the html file will still be rendered instead.

<h1 style="color: rgb(0, 0, 0); font-family: Times; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Advanced rules</h1>

Option | Name | Value | Default | Description
-- | -- | -- | -- | --
Cache control header value | cacheControl | string | - | Optionally specify a custom Cache-Control HTTP header value.
Serve hidden and dot files | hiddenDotFiles | true/false | false | Allow requesting hidden and dot files.
Allow file upload | upload | true/false | false | Allows PUT/POST requests.
Allow replacing files | replace | true/false | false | Allows PUT/POST requests to files that already exist.
Allow deleting files | delete | true/false | false | Allows DELETE requests.
Always use static directory listing | staticDirectoryListing | true/false | false | Disables JavaScript on the directory listing page, if it's enabled.
Show hidden and dot files in directory listing | hiddenDotFilesDirectoryListing | true/false | true | If hidden and dot files are enabled, determines if they will be shown in the directory listing. This includes .swshtaccess files.
Enable .swshtaccess configuration files | htaccess | true/false | false | You can use .swshtaccess files to set additional rules per directory. Learn more here.
Allow reading .swshtaccess files | htaccessRead | true/false | false | If serving hidden and dot files is enabled, turn on this option to also enable serving .swshtaccess files.
Allow modifying .swshtaccess files | htaccessWrite | true/false | false | If allow file upload is enabled, additionally allows PUT and POST requests to .swshtaccess files.
Allow deleting .swshtaccess files | htaccessDelete | true/false | false | If allow file deletion is enabled, additionally allows DELETE requests to .swshtaccess files.

<h1 style="color: rgb(0, 0, 0); font-family: Times; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Error Pages</h1>

Option | Name | Value | Default | Description
-- | -- | -- | -- | --
Custom 404 error page | custom404 | path string | - | File path to a custom 404 page. Will fallback to default 404 page if value is empty or file does not exist.
Custom 403 error page | custom403 | path string | - | File path to a custom 403 page. Will fallback to default 404 page if value is empty or file does not exist.
Custom 401 error page | custom401 | path string | - | File path to a custom 401 page. Will fallback to default 404 page if value is empty or file does not exist.
Custom 400 error page | custom400 | path string | - | File path to a custom 400 page. Will fallback to default 400 page if value is empty or file does not exist.
Custom error path variable | customErrorReplaceString | string | - | Optionally specify a custom string that will be looked for in your error pages and replaced with the current path. For example, if your custom 404 page included: "The file at {{PATH}} does not exist" and you set this option to "{{PATH}}", when your file is served it would say "The file at /example.txt does not exist".

<h1 style="color: rgb(0, 0, 0); font-family: Times; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Security</h1>

Option | Name | Value | Default | Description
-- | -- | -- | -- | --
Enable HTTPS | https | true/false | false | Make server accessible over a secure connection (https) instead of just http.
Custom HTTPS cerificate | httpsCert | string | - | Optionally override this option to provide a custom HTTPS certificate.
Custom HTTPS key | httpsKey | string | - | Optionally override this option to provide a custom HTTPS key.
Enable HTTP Basic authentication | httpAuth | true/false | false | Require authentication using the basic HTTP protocol. Specify a username and password in the httpAuthUsername and httpAuthPassword options. If either option is missing or invalid, the web server will become inaccessible.
HTTP auth username | httpAuthUsername | string | - | Username for HTTP Basic authentication.
HTTP auth password | httpAuthPassword | string | - | Password for HTTP Basic authentication. Stored in plain text.

**Comment by ethanaobrien** [comment]
Sounds like a good idea. I'll start working on the conversion when I get the chance. I think I'm going to just have an option in the code to specify the filename so if (for some reason) we change it in the future it wont take that long.

All the features look good. I need to make it to where it will check for both `.html` and `.htm` files on the exclude `.html` option but that shouldnt take long

One question, should we even have the `htaccessRead`, `htaccessWrite`, and `htaccessDelete` options? I don't see why the user would need this (and this would basically allow a hacker to run code remotely if turned on)

When I get the change I'll go through and change all the option names in the files

**Comment by terreng** [comment]
I agree, we can just get rid of `htaccessRead`, `htaccessWrite`, and `htaccessDelete`.

**Comment by terreng** [comment]
@ethanaobrien The `replace` option only takes effect if the `upload` option is enabled, right?

If the `htaccess` option is enabled, it should not be possible to upload/replace/delete any file named `.swshtaccess`. Otherwise it should be possible. Could you make sure this is the case?

**Comment by terreng** [comment]
@ethanaobrien Should we also add the option for a custom 429 error page?

**Comment by ethanaobrien** [comment]
>The replace option only takes effect if the upload option is enabled, right?

Correct

>If the htaccess option is enabled, it should not be possible to upload/replace/delete any file named .swshtaccess. Otherwise it should be possible. Could you make sure this is the case?

Already implemented

>Should we also add the option for a custom 429 error page?

I don't think so. This would just make more requests to the server (429 means too many requests)

>Actually, come to think of it, do we really need custom error pages for anything other than 404 and maybe 400?

I think we at least need 404 and 403. It makes sense to me to have a custom page for something like "not logged in" instead of just saying unauthorized. We dont really need a 400 page. It's your choice but I would recommend having at least a 403 and a 404 page

**Comment by terreng** [comment]
> It makes sense to me to have a custom page for something like "not logged in" instead of just saying unauthorized.

401 is unauthorized. So should we just have 401, 403, and 404?

**Comment by ethanaobrien** [comment]
>401 is unauthorized. So should we just have 401, 403, and 404?

Yes, that would make sense

**Comment by terreng** [comment]
> > 401 is unauthorized. So should we just have 401, 403, and 404?
> 
> Yes, that would make sense

Okay, I got rid of the `custom400` option.

**Comment by ethanaobrien** [comment]
@terreng 

Should we add a note in the how to or something that if the user wants a custom error page with any error, the user can just edit the settings and set `"custom'+httpcode` to true

**Comment by terreng** [comment]
> Should we add a note in the how to or something that if the user wants a custom error page with any error, the user can just edit the settings and set `"custom'+httpcode` to true

Are you saying the code always checks for a custom error path for every error code?

Also, does the code fallback to the default error page if there's no file at the specified path?

**Comment by ethanaobrien** [comment]
>Are you saying the code always checks for a custom error path for every error code?

Every time the error function is called yes. This function will see if there is a custom option and if not it will render the default page

>Also, does the code fallback to the default error page if there's no file at the specified path?

Correct

**Comment by terreng** [comment]
I will add a mention to the docs

**Comment by ethanaobrien** [comment]
403, 404, 429, 400, 401, 500,
