### ISSUE TITLE
Error on recreation of the root folder for a web server

### ISSUE THREAD

**Issue by RupprechJo** [terreng/simple-web-server#154]
**Description/Steps to reproduce**
Add a new server
Delete the root folder of the server and create a new one with the same name.
In the browser you get a 500, in the app you see this error: "File system error", "bookmarkDataIsStale - try recreating the bookmark".

The web server for chrome supported this use case. The reason is: Our build process recreates the whole folder

**Version information**
macOs, version 1.2.8 (26)

**Comment by RupprechJo** [comment]
Hm, I do not now many about macOS security bookmarks. I only know, when a directory is deleted, you have to recreate your file / file path object (depending on the language/framework you use). 

As it is, it is not usable at all for me, because you always have to reselect the same folder from the file system dialog

**Comment by terreng** [comment]
@RupprechJo This is a known issue with the Mac App Store version of the program only due to Apple's security measures. Please download the program from [our website](https://simplewebserver.org/download.html) instead to get around this limitation.

**Comment by terreng** [comment]
I'm going to leave this issue open because I think it would be nice to find a solution for Mac App Store users. One possible fix would be to ask the user to pick a directory a level (or a few levels) up, and then specify a path relative to that. Maybe a button to select the root/user folder to give the app access to everything. I'm not sure if the app store review team would have a problem with that.

**Comment by terreng** [comment]
We're adding a more descriptive error message that explains the problem and suggests downloading from our website to work around it. For now I'm closing this as won't fix.
