### ISSUE TITLE
GREAT FEATURE THATS EASY TO ADD

### ISSUE THREAD

**Issue by Eltoni07** [terreng/simple-web-server#182]
add a better gui on the website, check HTTP FS app on android, and check their design, something like that would make this the ultimate app.

**Comment by terreng** [comment]
While I appreciate your interest in bettering Simple Web Server, this isn't a very helpful or actionable issue. I'm going to take a moment to explain why:

- Lack of specificity: This issue is incredibly vague about what the suggestion is. The title doesn't describe what the suggestion is."add a better gui" is a broad statement and lacks specific details - It's unclear what aspects of the GUI could be improved or how. It would be a good idea to provide mockups or example designs.
- Subjectivity: Issues should ideally be based on objective shortcomings or feature gaps rather than subjective preferences. What constitutes a "better" GUI can vary greatly from person to person, which you haven't acknowledged here.
- Scope: It sounds like you're asking for a major redesign, which is no easy task. A suggestion like this would need to be backed by strong rationale, not a vague one sentence description. 

I maintain this project for free. I'm going to prioritize development efforts on core functionality, not GUI enhancements. I think the user interface is fine, and it's unclear what benefit there would be to investing my time into improving it.

If you would like to have a go at redesigning the app's interface, then you are more than welcome to open a pull request. 

I saw that this was your first issue on GitHub, so I hope this helps explain how you can make better issues in the future. In general, it's important to remember that GitHub projects like this one are maintained for free by busy people like myself. You can help respect maintainers by opening specific and detailed issues and avoiding the problems I outlined above. This will make it much more likely for your suggestions to be implemented or problems to be solved.

Please take a look at this quick Medium article for some good practices: https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f

**Comment by Eltoni07** [comment]
I can help, i can straight up give you the code. But if youre thinking that way👍its all goodOn Feb 8, 2024, at 04:13, Terren ***@***.***> wrote:﻿
While I appreciate your interest in bettering Simple Web Server, this isn't a very helpful or actionable issue. I'm going to take a moment to explain why:

Lack of specificity: This issue is incredibly vague about what the suggestion is. The title doesn't describe what the suggestion is."add a better gui" is a broad statement and lacks specific details - It's unclear what aspects of the GUI could be improved or how. It would be a good idea to provide mockups or example designs.
Subjectivity: Issues should ideally be based on objective shortcomings or feature gaps rather than subjective preferences. What constitutes a "better" GUI can vary greatly from person to person, which you haven't acknowledged here.
Scope: It sounds like you're asking for a major redesign, which is no easy task. A suggestion like this would need to be backed by strong rationale, not a vague one sentence description.

I maintain this project for free. I'm going to prioritize development efforts on core functionality, not GUI enhancements. I think the user interface is fine, and it's unclear what benefit there would be to investing my time into improving it.
If you would like to have a go at redesigning the app's interface, then you are more than welcome to open a pull request.
I saw that this was your first issue on GitHub, so I hope this helps explain how you can make better issues in the future. In general, it's important to remember that GitHub projects like this one are maintained for free by busy people like myself. You can help respect maintainers by opening specific and detailed issues and avoiding the problems I outlined above. This will make it much more likely for your suggestions to be implemented or problems to be solved.
Please take a look at this quick Medium article for some good practices: https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f

**Comment by terreng** [comment]
We would welcome and appreciate a code contribution via a pull request. Just keep in mind that design is subjective, so we may not merge everything.
