### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by gammaburst2024** [terreng/simple-web-server#188]
the item "log" does not exist in config.json

I've tried adding ""log": "true", at the lop level and within a server but logging does not start

Also the "server.log" file does not exist

downloaded from the apple app store

**Comment by terreng** [comment]
I just checked and it's working on my mac with the mac app store version. The `log` option goes at the top level. You need to make sure to completely restart the app if you have "Keep running when closed" enabled. Click "Stop & Quit" and then reopen it, and then it'll work.

Please let me know if these steps don't work for you. Thanks!

**Comment by gammaburst2024** [comment]
I’m on Mojave, could that be the reason? Was there logging on version 1.2.9 (27)?On Mar 5, 2024, at 15:32, Terren ***@***.***> wrote:﻿
I just checked and it's working on my mac with the mac app store version. The log option goes at the top level. You need to make sure to completely restart the app if you have "Keep running when closed" enabled. Click "Stop & Quit" and then reopen it, and then it'll work.
Please let me know if these steps don't work for you. Thanks!

**Comment by gammaburst2024** [comment]
It doesn’t seem like I can update since I’m running Mojave? (OSX 10.14)On Mar 6, 2024, at 13:22, Terren ***@***.***> wrote:﻿
Why don't you go ahead and update to 1.2.10 from the app store. That way we'll know that you definitely restarted the program.

**Comment by terreng** [comment]
It looks like the minimum supported macos version for the mac app store build went from 10.13 to 10.15 with the last update. Sorry about that. You'll have to download new versions [from our website](https://simplewebserver.org/download.html) instead of the App Store until you are able to update past Mojave.

I checked and I don't think there's anything significant that changed from 1.2.9 -> 1.2.10 which would have affected logging.

Could you confirm for me that you definitely tried adding the `log` option set to `true` at the top level in the config, and then fully restarting the program by clicking the "Stop & Quit" button?

**Comment by gammaburst2024** [comment]
Yes I definitely restarted without the “stay running when stopped” unchecked and the “log” option is at the top level. I’ll try to delete the program and reinstall On Mar 6, 2024, at 18:14, Terren ***@***.***> wrote:﻿
It looks like the minimum supported macos version for the mac app store build went from 10.13 to 10.15 with the last update. Sorry about that. You'll have to download new versions from our website instead of the App Store until you are able to update past Mojave.
I checked and I don't think there's anything significant that changed from 1.2.9 -> 1.2.10 which would have affected logging.
Could you confirm for me that you definitely tried adding the log option set to true at the top level in the config, and then fully restarting the program by clicking the "Stop & Quit" button?

**Comment by terreng** [comment]
I really don't know what to tell you, because it works on my machine. Are you sure that you're editing the right config file? (If you make it blank do all of your servers disappear?) Are you sure that logging isn't working? (Are you looking for the log file in the right place?)

@ethanaobrien Any ideas?

**Comment by gammaburst2024** [comment]
I tried reinstalling still not logging. 

I'm in 32bit Mojave and unable to update to a newer version which requires 64 bit

{
  "background": true,
  "updates": true,
  "theme": "system",
  "log": "true",
  "servers": [
    {
      "enabled": true,
      "path": "/Users/johnbruckner/Sites/bigshash.com",



no "server.log" file

**Comment by terreng** [comment]
It should be set to `true` _without_ quotes around it.
```
  "log": true,
```
instead of 
```
  "log": "true",
```

**Comment by gammaburst2024** [comment]
OH, duh.Yup that worked. Thank you.

**Comment by terreng** [comment]
Great!
