### ISSUE TITLE
Doesn't support OSX 10.14

### ISSUE THREAD

**Issue by magicmouse** [terreng/simple-web-server#202]
The documentation is not accurate; the current OSX download requires 10.15 or later, and unfortunately I am stuck with 10.14 because otherwise i lose the Adobe Create Suite which costs $1000.... and every other 32 bit app...  so please make an older version available for us poor 10.14 users.

**Comment by terreng** [comment]
Are you talking about the Mac App Store version, the .dmg download, or the .app download?

**Comment by magicmouse** [comment]
I tried both the .dmg download, and the .app download.

The Mac App Store will of course be 10.15 only as they are fairly mean in the store.

**Comment by terreng** [comment]
It looks like Chromium no longer supports macOS 10.14 which is why we've also had to drop support.

Per the [electron release notes](https://www.electronjs.org/blog/electron-27-0):
> **Removed: macOS 10.13 / 10.14 support**
> 
> macOS 10.13 (High Sierra) and macOS 10.14 (Mojave) are no longer supported by [Chromium](https://chromium-review.googlesource.com/c/chromium/src/+/4629466).
> 
> Older versions of Electron will continue to run on these operating systems, but macOS 10.15 (Catalina) or later will be required to run Electron v27.0.0 and higher.

I will update the documentation; thanks for pointing out the discrepancy. 

To use Simple Web Server on older versions of macOS, you can just [download one of the older versions](https://github.com/terreng/simple-web-server/releases) on GitHub. I think 1.2.9 should work. The only thing that's changed since then is the addition of new languages and bug fixes.

Please let me know if it works and I'll update the documentation. Thanks!

**Comment by magicmouse** [comment]
yes, 1.2.9 did the trick and still runs. 
Thanks for the help and for building this essential tool
Firefox allows the user to load JS files from their own hard drive, but Google is ridiculous.

e

**Comment by terreng** [comment]
Thanks for confirming that it works! I've updated the docs.
